# -*- coding: utf-8 -*-

#The above code declares utf8 encoding
#http://stackoverflow.com/questions/3170211/why-declare-unicode-by-string-in-python

classify_adm2_names = {
"Acul du Nord":"Acul du Nord",
"Anse D'Ainault":"Anse D'Ainault",
"Anse Ã  Veau":"Anse Ã  Veau",
"ANSE-à-VEAU":"Anse Ã  Veau",
"Aquin":"Aquin",
"Arcahaie":"Arcahaie",
"L'ARCAHAIE":"Arcahaie",
"Bainet":"Bainet",
"Belle Anse":"Belle Anse",
"Borgne":"Borgne",
"BORGNE":"Borgne",
"Cap HaÃ¯tien":"Cap HaÃ¯tien",
"CAP-HAïTIEN":"Cap HaÃ¯tien",
"Cayes":"Cayes",
"Cerca La Source":"Cerca La Source",
"CERCA LA SOURCE":"Cerca La Source",
"ChardonniÃ¨res":"ChardonniÃ¨res",
"Corail":"Corail",
"Coteaux":"Coteaux",
"Croix des Bouquets":"Croix des Bouquets",
"CROIX-DES-BOUQUETS":"Croix des Bouquets",
"Dessalines":"Dessalines",
"DESSALINES":"Dessalines",
"Fort-LibertÃ©":"Fort-LibertÃ©",
"GonaÃ¯ves":"GonaÃ¯ves",
"Grande RiviÃ¨re Du Nord":"Grande RiviÃ¨re Du Nord",
"Gros Morne":"Gros Morne",
"Hinche":"Hinche",
"Jacmel":"Jacmel",
"JACMEL":"Jacmel",
"JÃ©rÃ©mie":"JÃ©rÃ©mie",
"JéRéMIE":"JÃ©rÃ©mie",
"La Gonave":"La Gonave",
"Lascahobas":"Lascahobas",
"LimbÃ©":"LimbÃ©",
"LÃ©ogÃ¢ne":"LÃ©ogÃ¢ne",
"LéOGâNE":"LÃ©ogÃ¢ne",
"Marmelade":"Marmelade",
"MiragoÃ¢ne":"MiragoÃ¢ne",
"Mirebalais":"Mirebalais",
"MÃ´le Saint Nicolas":"MÃ´le Saint Nicolas",
"Ouanaminte":"Ouanaminte",
"Plaisance":"Plaisance",
"Port-Salut":"Port-Salut",
"Port-au-Prince":"Port-au-Prince",
"PORT-AU-PRINCE":"Port-au-Prince",
"Port-de-Paix":"Port-de-Paix",
"Saint Louis du Nord":"Saint Louis du Nord",
"Saint RaphaÃ«l":"Saint RaphaÃ«l",
"Saint-Marc":"Saint-Marc",
"SAINT-MARC":"Saint-Marc",
"Trou du Nord":"Trou du Nord",
"ValiÃ¨res":"ValiÃ¨res",}
