classify_adm3_names = {
"ABRICOTS":"ABRICOTS",
"ACUL DU NORD":"ACUL DU NORD",
#"L'ACUL" double check
"ANSE A FOLEUR":"ANSE A FOLEUR",
"ANSE ROUGE":"ANSE ROUGE",
"ANSE-A-GALET":"ANSE-A-GALET",
"ANSE-A-GALETS":"ANSE-A-GALET",
"ANSE-A-PITRE":"ANSE-A-PITRE",
"ANSE-A-VEAU":"ANSE-A-VEAU",
"ANSE A VEAU":"ANSE-A-VEAU",
"ANSE-D'AINAULT":"ANSE-D'AINAULT",
"AQUIN":"AQUIN",
"ARCAHAIE":"ARCAHAIE",
"ARNIQUET":"ARNIQUET",
"BAHON":"BAHON",
"BAIE DE HENNE":"BAIE DE HENNE",
"BAINET":"BAINET",
"BARADERES":"BARADERES",
"BAS LIMBE":"BAS LIMBE",
"BASSIN BLEU":"BASSIN BLEU",
"BEAUMONT":"BEAUMONT",
"BELLADERE":"BELLADERE",
"BELLE ANSE":"BELLE ANSE",
"BOMBARDOPOLIS":"BOMBARDOPOLIS",
"BONBON":"BONBON",
"BORGNE":"BORGNE",
"BOUCAN CARRE":"BOUCAN CARRE",
"BOUCAN CARR":"BOUCAN CARRE",
"CABARET":"CABARET",
"CAMP PERRIN":"CAMP PERRIN",
"CAP HAITIEN":"CAP HAITIEN",
"CAP-HAITIEN":"CAP HAITIEN",
"CAPOTILLE":"CAPOTILLE",
"CARACOL":"CARACOL",
#"CARACOL":"CARACOL",
"CARICE":"CARICE",
"CARREFOUR":"CARREFOUR",
"CARREFOUR LE MORT":"CARREFOUR",
"CAVAILLON":"CAVAILLON",
"CAYES-JACMEL":"CAYES-JACMEL",
"CECA LA SOURCE":"CECA LA SOURCE",
"CERCA LA SOURCE":"CECA LA SOURCE",
"CERCA CARVAJAL":"CERCA CARVAJAL",
"CHAMBELLAN":"CHAMBELLAN",
"CHANSOLME":"CHANSOLME",
"CHANTAL":"CHANTAL",
"CHARDONNIERES":"CHARDONNIERES",
"CORAIL":"CORAIL",
"CORNILLON / GRD BOIS":"CORNILLON / GRD BOIS",
"COTE-DE-FER":"COTE-DE-FER",
"COTEAUX":"COTEAUX",
"CROIX-DES-BOUQUES":"CROIX-DES-BOUQUES",
"CROIX-DES-BOUQUETS":"CROIX-DES-BOUQUES",
"DAME-MARIE":"DAME-MARIE",
"DELMAS":"DELMAS",
"DESDUNES":"DESDUNES",
"DESSALINES / MARCHANDES":"DESSALINES / MARCHANDES",
"DESSALINES":"DESSALINES / MARCHANDES",
"DONDON":"DONDON",
"ENNERY":"ENNERY",
"FERRIER":"FERRIER",
"FONDS-VERRETTES":"FONDS-VERRETTES",
"FORT LIBERTE":"FORT LIBERTE",
"GANTHIER":"GANTHIER",
"GONAIVES":"GONAIVES",
"GRAND GOSIER":"GRAND GOSIER",
"GRAND-GOAVE":"GRAND-GOAVE",
"GRAND GOAVE":"GRAND-GOAVE",
"GRANDE RIVIERE DU NORD":"GRANDE RIVIERE DU NORD",
"GRANDE SALINE":"GRANDE SALINE",
"GRESSIER":"GRESSIER",
"GROS MORNE":"GROS MORNE",
"HINCHE":"HINCHE",
"ILE A VACHE":"ILE A VACHE",
"JACMEL":"JACMEL",
"JEAN RABEL":"JEAN RABEL",
"JEREMIE":"JEREMIE",
"KENSCOFF":"KENSCOFF",
"L'AZILE":"L'AZILE",
"L'ESTERE":"L'ESTERE",
"LA CHAPELLE":"LA CHAPELLE",
"LA TORTUE":"LA TORTUE",
"LA VALLEE":"LA VALLEE",
"LA VICTOIRE":"LA VICTOIRE",
"LASCAHOBAS":"LASCAHOBAS",
"LEOGANE":"LEOGANE",
"LES ANGLAIS":"LES ANGLAIS",
"LES CAYES":"LES CAYES",
"LES IROIS":"LES IROIS",
"LIMBE":"LIMBE",
"LIMONADE":"LIMONADE",
"MAISSADE":"MAISSADE",
"MANICHE":"MANICHE",
"MARIGOT":"MARIGOT",
"MARMELADE":"MARMELADE",
"MILOT":"MILOT",
"MIRAGOANE":"MIRAGOANE",
"MIREBALAIS":"MIREBALAIS",
"MOLE SAINT NICOLAS":"MOLE SAINT NICOLAS",
"MOMBIN CROCHU":"MOMBIN CROCHU",
"MONT ORGANISE":"MONT ORGANISE",
"MORON":"MORON",
"OUANAMINTHE":"OUANAMINTHE",
"PERCHES":"PERCHES",
"PESTEL":"PESTEL",
"PETION-VILLE":"PETION-VILLE",
"PETIONVILLE":"PETION-VILLE",
"PETIT TROU DE NIPPES":"PETIT TROU DE NIPPES",
"PETIT-GOAVE":"PETIT-GOAVE",
"PETIT GOAVE":"PETIT-GOAVE",
"PETITE RIVIERE DE L'ARTI":"PETITE RIVIERE DE L'ARTI",
"PETITE RIVIERE DE NIPPES":"PETITE RIVIERE DE NIPPES",
#'PETITE RIVI' need to match to right none
"PIGNON":"PIGNON",
"PILATE":"PILATE",
"PLAINE DU NORD":"PLAINE DU NORD",
"PLAISANCE":"PLAISANCE",
"POINTE A RAQUETTE":"POINTE A RAQUETTE",
"PORT DE PAIX":"PORT DE PAIX",
"PORT-DE-PAIX":"PORT DE PAIX",
"PORT MARGOT":"PORT MARGOT",
"PORT-A-PIMENT":"PORT-A-PIMENT",
"PORT-AU-PRINCE":"PORT-AU-PRINCE",
"PORT-AU-PRINCE (BLANCHARD)":"PORT-AU-PRINCE",
"PORT-AU-PRINCE (TITANYEN)":"PORT-AU-PRINCE",
"PORT-AU-PRINCE (MARTISSANT)":"PORT-AU-PRINCE",
"PORT-AU-PRINCE (PACOT)":"PORT-AU-PRINCE",
"PORT-AU-PRINCE (CIT":"PORT-AU-PRINCE",
"PORT-AU-PRINCE (CAMP":"PORT-AU-PRINCE",
"PORT-AU-PRINCE (MARTISSANT)":"PORT-AU-PRINCE",
"PORT -AU-PRINCE (TABARRE)":"PORT-AU-PRINCE",
"PORT-SALUT":"PORT-SALUT",
"QUARTIER MORIN":"QUARTIER MORIN",
"RANQUITTE":"RANQUITTE",
"ROCHE-A-BATEAU":"ROCHE-A-BATEAU",
"ROSEAUX":"ROSEAUX",
"SAINT LOUIS DU NORD":"SAINT LOUIS DU NORD",
"SAINT-LOUIS DU NORD":"SAINT LOUIS DU NORD",
"SAINT-MARC":"SAINT-MARC",
"SAINT-MICHEL":"SAINT-MICHEL",
"SAINTE SUZANE":"SAINTE SUZANE",
"ST. SUZANNEE":"SAINTE SUZANE",
"SAUT-D'EAU":"SAUT-D'EAU",
"SAVANETTE":"SAVANETTE",
"ST. JEAN DU SUD":"ST. JEAN DU SUD",
"ST. LOUIS DU SUD":"ST. LOUIS DU SUD",
"ST. RAPHAEL":"ST. RAPHAEL",
"TERRE NEUVE":"TERRE NEUVE",
"TERRIER ROUGE":"TERRIER ROUGE",
"THIOTTE":"THIOTTE",
"THOMASSIQUE":"THOMASSIQUE",
"THOMAZEAU":"THOMAZEAU",
"THOMONDE":"THOMONDE",
"TIBURON":"TIBURON",
"TORBECK":"TORBECK",
"TROU DU NORD":"TROU DU NORD",
"VALLIERE":"VALLIERE",
"VERRETTES":"VERRETTES",}

'''
un-matched adm3 names from MMEX: 
VAUDREUIL
NOUVELLE CITE
FOND PARISIEN
SEGUIN
ROCHE BLANCHE
FOND PARISIEN
LA JEUNE
BOHOC
BOD MER LIMBE
TRICON
DESCHAPELLES
CANGE
BONNE FIN
ROBILLARD
BOIS DE LANCE
PONT-SOND
BERTRAND
DUVAL
ST. BONIFACE HOSPITAL SATELLITE CLINIC
PETIT BOURG DU BORGNE
PASSE CATABOIS
FOND DES BLANCS
JUAMPAS
FORT ST. MICHEL
LA ROMANA
TEGUCIGALPA
CYVADIER
ROCHE BLANCHE
PONT SONDE

un-matched ad3 names from Haiti Aid Map:
CITE SOLEIL

    
'''    
    
