classify_service_types = {'Cardiovascular': 'Cardiovascular',
	'Cardiology': 'Cardiovascular',
 	'Dental': 'Dental',
 	'Dentistry': 'Dental',
  	'Diabetes': 'Diabetes',
   	'Emergency': 'Emergency',
   	'Emergency Medicine': 'Emergency',
   	'Environmental health': 'Environmental health',
   	'environmental_health': 'Environmental health',
	'General consultation': 'General consultation',
	'Family or General Practice': 'General consultation',
	'Internal Medicine': 'General consultation',
	'Endocrinology': 'General consultation',
    'Hypertension': 'Hypertension',
    'Intensive care': 'Intensive care',
    'Oncology' : 'Intensive care',
	'Laboratory': 'Laboratory',
	'Lab Services': 'Laboratory',
	'Radiology': 'Laboratory',
	'Malaria': 'Malaria',
	'ORL': 'ORL',
	'Otolaryngology': 'ORL',
	'Orl ': 'ORL',
	'ObGyn': 'ObGyn',
	'Cervical cancer screening': 'ObGyn',
	'Obstetrics and Gynecology': 'ObGyn',
	'Obgyn': 'ObGyn',
	'Operating room': 'Operating room',
	'Palliative care': 'Palliative care',
	'Pediatrics': 'Pediatrics',
	'Pharmacy':'Pharmacy',
	'Physical therapy':'Physical therapy',
	'Orthotist':'Physical therapy',
	'Orthopedics':'Physical therapy',
	'Physical Therapy':'Physical therapy',
	'Prosthetic Services':'Physical therapy',
	'Free obstetric care program': 'Obstetric care',
	#'free_obstetric_care_program': 'Free obstetric care program', 
	'Psychology Service': 'Psychology service',
	'Psychology service': 'Psychology service',
	'Pychological Health': 'Psychology service',
	'Psychiatry': 'Psychology service',
	'Neurology': 'Psychology service',
	'Surgery': 'Surgery',
	'Anesthesiology': 'Surgery',
	'Burn care': 'Surgery',
	'General Surgery': 'Surgery',
	'Maxillofacial Surgery': 'Surgery',
	'Orthopedic Surgery': 'Surgery',
	'Pediatric Surgery': 'Surgery',
	'Plastic Surgery': 'Surgery',
	'Urology': 'Surgery',
	'Gynecological Surgery' : 'Surgery',
	'Vaccination (PEV)': 'Vaccination (PEV)',
	'Vaccinations': 'Vaccination (PEV)',
	'Vaccination': 'Vaccination (PEV)',
	'Clinical Services': 'Clinical services',
	'Nurse Practitioner': 'Clinical services',
	'Contagious Diseases': 'Contagious diseases',
	'Tuberculosis Treatment': 'Contagious diseases',
	'Infectious Disease': 'Contagious diseases',
	'Environmental Health': 'Environmental health',
	'gender_based_violence': 'Gender based violence',
	'Gender based violence': 'Gender based violence',
	'HIV-SIDA Infections': 'HIV-SIDA infections',
	'HIV Treatment': 'HIV-SIDA infections',
	'Infant Health': 'Infant health', 
	'Neonatology': 'Infant health', 
	'Maternity Health': 'Maternity health',
	'Midwife': 'Maternity health',
	'Nutrition': 'Nutrition',
	'Re-education': 'Re-education',
	'Family planning services': 'Re-education',
	'Ophthalmology' : 'EyeCare',
	'Optometry' : 'EyeCare', 
	'Rehabilitation Medicine' : 'Other',
	'Audiology' : 'Other',
	'Dermatology': 'Other',
	'Biomed engineer/equip repair':'Other',
	'Other':'Other',
	'Physician Assistant' : 'Other'}
    
    
    
